export const WHATSAPP='5491178234289';
export const IVA_RATE=0.21;
export const API_BASE='https://gm-electronics-api.onrender.com';
export function hasPrice(value){return value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))&&Number(value)>0}
export function formatARS(value){return hasPrice(value)?new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value)):'Consultar precio'}
export function stockLabel(value){return value===true?'Disponible':'Consultar disponibilidad'}
export function canOrder(variant){return variant?.stock_disponible===true&&hasPrice(variant.precio_pesos)}
export function defaultVariant(product){return product.variantes?.find(canOrder)||product.variantes?.find(v=>v.stock_disponible===true)||product.variantes?.[0]}
export function consultUrl(product,variant=defaultVariant(product)){const missing=[];if(variant?.stock_disponible!==true)missing.push('disponibilidad');if(!hasPrice(variant?.precio_pesos))missing.push('precio');return 'https://wa.me/'+WHATSAPP+'?text='+encodeURIComponent('Hola Gonzalo, quisiera consultar '+(missing.join(' y ')||'por este producto')+': '+product.nombre+' | Código: '+(variant?.codigo||product.id)+(variant?.color?' | Color: '+variant.color:''))}
export function referencePrice(product){const variants=product.variantes||[];const available=variants.filter(v=>v.stock_disponible===true&&hasPrice(v.precio_pesos));const priced=available.length?available:variants.filter(v=>hasPrice(v.precio_pesos));return priced.length?Math.min(...priced.map(v=>Number(v.precio_pesos))):null}
export function comparePrice(a,b,direction){const left=referencePrice(a),right=referencePrice(b);if(left===null)return right===null?String(a.id).localeCompare(String(b.id)):1;if(right===null)return -1;return (left-right)*(direction==='priceDesc'?-1:1)||String(a.id).localeCompare(String(b.id))}
export async function apiGet(path,{signal}={}){const controller=new AbortController();const abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)controller.abort();const timeout=setTimeout(abort,60000);try{const response=await fetch(API_BASE+path,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error('No pudimos actualizar la información.');return await response.json()}finally{clearTimeout(timeout);signal?.removeEventListener('abort',abort)}}
export async function loadCatalog(signal){const first=await apiGet('/api/v1/products?limit=100&page=1',{signal});if(!Array.isArray(first.data)||!Number.isInteger(first.pagination?.pages)||first.pagination.pages>100)throw new Error('Respuesta de catálogo inválida');const pages=[first];for(let page=2;page<=first.pagination.pages;page+=3){const group=await Promise.all(Array.from({length:Math.min(3,first.pagination.pages-page+1)},(_,i)=>apiGet('/api/v1/products?limit=100&page='+(page+i),{signal})));pages.push(...group)}const products=pages.flatMap(page=>page.data);if(products.length!==first.pagination.total||new Set(products.map(p=>p.id)).size!==products.length)throw new Error('El catálogo se está actualizando.');return products}
export function readSaved(key,fallback){try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback}catch{return fallback}}
export function save(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Browsing and ordering continue when storage is unavailable. */}}
export function savedCart(){const rows=readSaved('gm-cart-v2',[]);if(!Array.isArray(rows))return [];const seen=new Set();return rows.filter(row=>{if(!row||typeof row.id!=='string'||!row.producto_id||!Number.isInteger(row.qty)||row.qty<1||row.qty>999||seen.has(row.id)||!hasPrice(row.precio_pesos))return false;seen.add(row.id);return true}).slice(0,100)}
export function savedProfile(){const row=readSaved('gm-profile-v1',{});return Object.fromEntries(['name','email','phone','business'].map(key=>[key,typeof row?.[key]==='string'?row[key].slice(0,200):'']))}
export function cartLine(product,variant){return {...product,id:variant.api_id,producto_id:product.id,nombre:product.nombre,precio_pesos:variant.precio_pesos,stock_disponible:variant.stock_disponible,variantes:[variant],imagen:variant.imagenes?.[0]||product.imagen}}
export async function refreshCart(cart){const products=await Promise.all([...new Set(cart.map(row=>row.producto_id))].map(id=>apiGet('/api/v1/products/'+encodeURIComponent(id))));const byId=new Map(products.map(response=>[response.data.id,response.data]));return cart.map(row=>{const product=byId.get(row.producto_id);const variant=product?.variantes.find(v=>v.api_id===row.id);return variant?{...cartLine(product,variant),qty:row.qty}:{...row,stock_disponible:null,precio_pesos:null}})}
