import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import products from './data/productos.json';
import './styles.css';

const WHATSAPP='5491178234289';
const EMAIL='gonzalo.m.martin@gmail.com';
const IVA_RATE=0.21; // Pendiente de confirmar como tasa comercial definitiva.
const categories=[...new Set(products.map(p=>p.categoria).filter(Boolean))];
const formatARS=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n)||0);
const cleanName=n=>String(n||'').replace(/\s+/g,' ').trim();

function Logo(){return <div className="logo"><span className="gm">GM</span><span className="electronics">ELECTRONICS</span></div>}

function App(){
 const [query,setQuery]=useState(''),[cat,setCat]=useState('Todas'),[sort,setSort]=useState('relevance');
 const [cart,setCart]=useState([]),[invoice,setInvoice]=useState(false),[cartOpen,setCartOpen]=useState(false),[detail,setDetail]=useState(null);
 const [menuOpen,setMenuOpen]=useState(true),[accountOpen,setAccountOpen]=useState(false),[checkoutOpen,setCheckoutOpen]=useState(false);
 const [customer,setCustomer]=useState({name:'',business:'',phone:'',email:'',address:'',payment:'Transferencia bancaria'});\n const [emailStatus,setEmailStatus]=useState('');
 const [account,setAccount]=useState({name:'',email:'',phone:'',business:''});

 const filtered=useMemo(()=>{let a=products.filter(p=>{const q=query.toLowerCase();return(cat==='Todas'||p.categoria===cat)&&(!q||[p.nombre,p.descripcion,p.categoria,p.id,...(p.variantes||[]).map(v=>v.codigo)].join(' ').toLowerCase().includes(q))});if(sort==='priceAsc')a.sort((x,y)=>x.precio_pesos-y.precio_pesos);if(sort==='priceDesc')a.sort((x,y)=>y.precio_pesos-x.precio_pesos);return a},[query,cat,sort]);
 const featured=products.slice(0,4);
 const add=p=>setCart(c=>{const found=c.find(x=>x.id===p.id);return found?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});
 const remove=id=>setCart(c=>c.flatMap(x=>x.id===id?(x.qty>1?[{...x,qty:x.qty-1}]:[]):[x]));
 const subtotal=cart.reduce((s,x)=>s+x.precio_pesos*x.qty,0),iva=invoice?subtotal*IVA_RATE:0,total=subtotal+iva;
 const scrollTo=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 const orderMessage=useMemo(()=>{const lines=cart.map(x=>`• ${cleanName(x.nombre)} x${x.qty} — ${formatARS(x.precio_pesos*x.qty)}`).join('\n');return `Hola Gonzalo, quiero hacer un pedido a GM Electronics.\n\nCliente: ${customer.name}\nEmpresa/comercio: ${customer.business||'-'}\nTeléfono: ${customer.phone}\nEmail: ${customer.email||'-'}\nDirección: ${customer.address||'-'}\nPago: ${customer.payment}\n\n${lines}\n\nSubtotal: ${formatARS(subtotal)}\n${invoice?`IVA 21%: ${formatARS(iva)}\nTotal: ${formatARS(total)}`:`Total: ${formatARS(total)} (sin IVA)`}`},[cart,customer,subtotal,iva,total,invoice]);
 const waUrl=`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(orderMessage)}`;
 const beginCheckout=()=>{if(!cart.length)return;setCartOpen(false);setCheckoutOpen(true)};
 const phoneValid=/^\\d{8,13}$/.test(customer.phone);\n const emailValid=/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(customer.email);\n const validCustomer=Boolean(customer.name.trim()&&phoneValid&&emailValid);\n const sendEmail=async()=>{if(!validCustomer)return;setEmailStatus('Enviando...');try{const r=await fetch('/api/send-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,items:cart,invoice,subtotal,iva,total})});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo enviar');setEmailStatus('Pedido enviado a GM Electronics.');}catch(e){setEmailStatus('No se pudo enviar automáticamente. Podés usar WhatsApp o el correo preparado.');}};
 const updateCustomer=(key,value)=>setCustomer(c=>({...c,[key]:value}));

 return <div className="app">
  <header className="topbar"><Logo/><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar productos, códigos o marcas..."/><span>⌕</span></div><div className="head-actions"><a className="wa-head" href={`https://wa.me/${WHATSAPP}`} target="_blank" rel="noreferrer">WhatsApp<br/><b>11 7823-4289</b></a><button className="account-head" onClick={()=>setAccountOpen(true)} aria-label="Mi cuenta">♙ <small>Mi cuenta</small></button><button className="cart-head-btn" onClick={()=>setCartOpen(true)} aria-label="Pedido">🛒 <span>{cart.reduce((s,x)=>s+x.qty,0)}</span></button></div></header>

  <div className="layout"><aside className={`sidebar ${menuOpen?'open':''}`}>
    <div className="menu-top"><span>☷ <b>MENÚ</b></span><button onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?'‹':'›'}</button></div>
    <nav className="side-nav">
      <button onClick={()=>scrollTo('inicio')}>⌂ <span>Inicio</span></button><button onClick={()=>scrollTo('destacados')}>★ <span>Productos destacados</span></button><button onClick={()=>scrollTo('catalogo')}>▦ <span>Catálogo</span></button>
      <button className="category-toggle" onClick={()=>setMenuOpen(true)}>☰ <span>Categorías</span><b>⌄</b></button>
      {menuOpen&&<div className="category-list">{categories.map(c=><button key={c} onClick={()=>{setCat(c);scrollTo('catalogo')}}>{c}<span>›</span></button>)}</div>}
      <div className="side-divider"/><button onClick={()=>scrollTo('como-comprar')}>✓ <span>Cómo comprar</span></button><button onClick={()=>scrollTo('quienes-somos')}>◎ <span>Quiénes somos</span></button><button onClick={beginCheckout}>＋ <span>Hacé tu pedido</span></button><button onClick={()=>setAccountOpen(true)}>♙ <span>Mi cuenta</span></button>
    </nav>
    <div className="side-contact"><strong>¿Necesitás ayuda?</strong><span>Atención directa por WhatsApp</span><a href={`https://wa.me/${WHATSAPP}`} target="_blank" rel="noreferrer">Hablar con Gonzalo →</a></div>
  </aside>

  <main>
    <section id="inicio" className="hero"><div className="hero-copy"><span className="pill">DISTRIBUCIÓN MAYORISTA</span><h1>Tecnología de punta,<br/><em>directo a tu negocio.</em></h1><p>Electrónica y accesorios de marcas nacionales e internacionales, con precios mayoristas, atención directa y una forma simple de armar tus pedidos.</p><div className="benefits"><b>⚡ Precios mayoristas</b><b>◇ Sin mínimo general</b><b>▣ Envíos a todo el mundo</b></div><button className="primary" onClick={()=>scrollTo('catalogo')}>Ver catálogo →</button></div><div className="hero-art image-hero"><img src="/hero-gm.svg" alt="GM Electronics - distribución mayorista de electrónica"/></div></section>
    <section className="cat-strip">{categories.slice(0,8).map(c=><button key={c} onClick={()=>{setCat(c);scrollTo('catalogo')}}><div className="cat-icon">{c[0]}</div><span>{c}</span></button>)}<button onClick={()=>{setCat('Todas');scrollTo('catalogo')}}><div className="cat-icon">→</div><span>Ver todas</span></button></section>
    <section id="destacados" className="featured"><div className="section-head"><div><span className="eyebrow">SELECCIÓN GM</span><h2>Productos destacados</h2></div><button onClick={()=>scrollTo('catalogo')}>Ver todo el catálogo →</button></div><div className="cards">{featured.map(p=><ProductCard key={p.id} p={p} add={add} detail={setDetail}/>)}</div></section>
    <section id="catalogo" className="catalog"><div className="catalog-tools"><div><span className="eyebrow">CATÁLOGO COMPLETO</span><h2>Encontrá lo que necesitás</h2><p>Buscá por producto, marca, categoría o código.</p></div><div className="catalog-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en todo el catálogo..."/></div></div><div className="filter-bar"><div className="filter-label">Filtrar catálogo</div><select value={cat} onChange={e=>setCat(e.target.value)}><option value="Todas">Todas las categorías</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">Más relevantes</option><option value="priceAsc">Precio menor</option><option value="priceDesc">Precio mayor</option></select><span className="result-count">{filtered.length} productos</span></div><div className="grid">{filtered.map(p=><ProductCard key={p.id} p={p} add={add} detail={setDetail}/>)}</div></section>
    <section id="como-comprar" className="info-section"><div><span className="eyebrow">CÓMO COMPRAR</span><h2>Armá tu pedido en minutos.</h2><p>Elegí productos, indicá cantidades y completá tus datos. Después podés enviarnos el pedido por WhatsApp o prepararlo para enviarlo por email.</p></div><div className="steps"><div><b>01</b><span>Elegí tus productos</span></div><div><b>02</b><span>Completá tus datos</span></div><div><b>03</b><span>Enviá el pedido</span></div></div></section>
    <section id="quienes-somos" className="about-section"><div className="about-mark">GM</div><div><span className="eyebrow">GM ELECTRONICS</span><h2>Tecnología para hacer crecer tu negocio.</h2><p>Distribución mayorista, atención directa y un catálogo pensado para comercios que necesitan comprar tecnología de manera simple.</p><div className="about-points"><span>✓ Marcas nacionales e internacionales</span><span>✓ Precios visibles</span><span>✓ Atención directa</span><span>✓ Envíos desde Zona Oeste</span></div></div></section>
    <section className="trust"><div><b>✓</b><span><strong>Precios mayoristas</strong>Precios visibles y claros.</span></div><div><b>₿</b><span><strong>Medios de pago</strong>Efectivo o transferencia.</span></div><div><b>▤</b><span><strong>Facturación</strong>Según modalidad elegida.</span></div><div><b>▱</b><span><strong>Envíos</strong>Desde Zona Oeste.</span></div><div><b>◉</b><span><strong>Atención directa</strong>Gonzalo · 11 7823-4289</span></div></section>
  </main></div>
  <footer><Logo/><div>GM Electronics · Distribución mayorista<br/><a href={`mailto:${EMAIL}`}>{EMAIL}</a></div><div>Zona Oeste · Argentina<br/>Envíos a todo el mundo</div></footer>

  {cartOpen&&<div className="overlay" onClick={()=>setCartOpen(false)}><div className="cart" onClick={e=>e.stopPropagation()}><div className="cart-head"><div><span className="eyebrow">GM ELECTRONICS</span><h2>Tu pedido</h2></div><button onClick={()=>setCartOpen(false)}>×</button></div>{cart.length===0?<div className="empty-box"><p>Todavía no agregaste productos.</p><button className="primary" onClick={()=>{setCartOpen(false);scrollTo('catalogo')}}>Ver catálogo</button></div>:<><div className="cart-items">{cart.map(x=><div className="cart-row" key={x.id}><div><b>{cleanName(x.nombre)}</b><small>{formatARS(x.precio_pesos)} c/u</small></div><div className="qty"><button onClick={()=>remove(x.id)}>−</button>{x.qty}<button onClick={()=>add(x)}>+</button></div></div>)}</div><div className="invoice"><label><input type="checkbox" checked={invoice} onChange={e=>setInvoice(e.target.checked)}/> Solicito factura</label><small>El IVA se calcula al solicitar factura. Tasa configurable.</small></div><div className="totals"><span>Subtotal <b>{formatARS(subtotal)}</b></span>{invoice&&<span>IVA <b>{formatARS(iva)}</b></span>}<strong>Total <b>{formatARS(total)}</b></strong></div><button className="primary full" onClick={beginCheckout}>Continuar con mis datos →</button></>}</div></div>}

  {checkoutOpen&&<div className="overlay"><div className="checkout modal-wide"><div className="cart-head"><div><span className="eyebrow">PASO 2 DE 2</span><h2>Datos del pedido</h2></div><button onClick={()=>setCheckoutOpen(false)}>×</button></div><p className="checkout-intro">Necesitamos estos datos para saber quién realiza el pedido y poder contactarte.</p><div className="form-grid"><label>Nombre y apellido *<input value={customer.name} onChange={e=>updateCustomer('name',e.target.value)} placeholder="Ej. Juan Pérez"/></label><label>Teléfono / WhatsApp *<input inputMode="numeric" pattern="[0-9]{8,13}" maxLength="13" value={customer.phone} onChange={e=>updateCustomer('phone',e.target.value)} placeholder="Solo números · 8 a 13 dígitos"/>{customer.phone&&!phoneValid&&<small className="field-error">Usá únicamente números, entre 8 y 13 dígitos.</small>}</label><label>Comercio / empresa<input value={customer.business} onChange={e=>updateCustomer('business',e.target.value)} placeholder="Nombre del comercio"/></label><label>Email *<input type="email" value={customer.email} onChange={e=>updateCustomer('email',e.target.value)} placeholder="correo@ejemplo.com"/>{customer.email&&!emailValid&&<small className="field-error">Ingresá un email válido, por ejemplo nombre@dominio.com.</small>}</label><label className="full-field">Dirección / localidad<input value={customer.address} onChange={e=>updateCustomer('address',e.target.value)} placeholder="Dirección, localidad, provincia"/></label><label>Medio de pago<select value={customer.payment} onChange={e=>updateCustomer('payment',e.target.value)}><option>Transferencia bancaria</option><option>Efectivo (a contra entrega)</option></select></label></div>{!validCustomer&&<div className="form-note">Completá nombre, teléfono y email válidos para continuar.</div>}<div className="checkout-actions"><button className="secondary" onClick={()=>{setCheckoutOpen(false);setCartOpen(true)}}>← Volver</button><div><a className={`primary send-link ${validCustomer?'':'disabled'}`} href={validCustomer?waUrl:'#'} target={validCustomer?'_blank':undefined} rel="noreferrer" onClick={e=>{if(!validCustomer)e.preventDefault()}}>Enviar por WhatsApp ↗</a><button className={`mail mail-button ${validCustomer?'':'disabled'}`} onClick={sendEmail} disabled={!validCustomer}>Enviar pedido por email</button></div></div><div className="email-note">El email se envía automáticamente a Gonzalo.M.Martin@gmail.com desde el servidor cuando la API de correo esté configurada en Vercel.{emailStatus&&<strong className="email-status">{emailStatus}</strong>}</div></div></div>}

  {accountOpen&&<div className="overlay" onClick={()=>setAccountOpen(false)}><div className="account-panel modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setAccountOpen(false)}>×</button><span className="eyebrow">MI CUENTA</span><h2>Tu perfil de cliente</h2><p>Guardá tus datos para que tus próximos pedidos sean más rápidos. Por ahora se almacenan en este navegador.</p><div className="form-grid"><label>Nombre<input value={account.name} onChange={e=>setAccount(a=>({...a,name:e.target.value}))}/></label><label>Teléfono<input value={account.phone} onChange={e=>setAccount(a=>({...a,phone:e.target.value}))}/></label><label>Comercio / empresa<input value={account.business} onChange={e=>setAccount(a=>({...a,business:e.target.value}))}/></label><label>Email<input type="email" value={account.email} onChange={e=>setAccount(a=>({...a,email:e.target.value}))}/></label></div><div className="account-features"><span>✓ Datos para futuros pedidos</span><span>✓ Acceso rápido al carrito</span><span>✓ Base para historial de pedidos</span></div><button className="primary full" onClick={()=>{setCustomer(c=>({...c,name:account.name||c.name,phone:account.phone||c.phone,business:account.business||c.business,email:account.email||c.email}));setAccountOpen(false)}}>Guardar mis datos</button></div></div>}

  {detail&&<div className="overlay" onClick={()=>setDetail(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>×</button><span className="pill">{detail.categoria}</span><h2>{cleanName(detail.nombre)}</h2><p>{detail.descripcion}</p><div className="detail-bottom"><strong>{formatARS(detail.precio_pesos)}</strong><span>Precio mayorista · IVA no incluido</span><button className="primary" onClick={()=>{add(detail);setDetail(null);setCartOpen(true)}}>Agregar al pedido</button></div></div></div>}
 </div>
}
function ProductCard({p,add,detail}){return <article className="card"><button className="photo" onClick={()=>detail(p)}><div className="placeholder">{(p.nombre||'GM').slice(0,2).toUpperCase()}</div></button><span className="tag">{p.categoria}</span><h3>{cleanName(p.nombre)}</h3><small>Código: {(p.variantes?.[0]?.codigo)??'—'}</small><div className="price">{formatARS(p.precio_pesos)}</div><div className="sub">Precio mayorista · IVA no incluido</div><button className="add" onClick={()=>add(p)}>Agregar al pedido</button></article>}
createRoot(document.getElementById('root')).render(<App/>);